import type { Metadata } from "next";
import localFont from "next/font/local";
import { JetBrains_Mono } from "next/font/google";
import classNames from "classnames";
import Providers from "@/app/Providers";
import Toolbar from "@/lib/components/common/Toolbar";
import "@/app/theme-config.css";
import "@/app/global.css";
import Footer from "@/lib/components/common/Footer";

const pretendard = localFont({
  src: "../public/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrainsmono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={classNames(pretendard.variable, jetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <body>
        <Providers>
          <Toolbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
